version: "3.8"

services:
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./frontend:/usr/src/app
        depends_on:
            - backend
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:
            - ./backend:/usr/src/app
        depends_on:
            - mongodb
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

    mongodb:
        build:
            context: .
            dockerfile: mongodb/Dockerfile
        ports:
            - 27018:27017
        env_file:
            - .env
        command:
            [
                "mongod",
                "--keyFile",
                "/usr/src/mongo.key",
                "--replSet",
                "rs0",
                "--bind_ip",
                "0.0.0.0",
            ]
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
