version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 5173:5173
        depends_on:
            - backend
        command: npm run dev
        develop:
            watch:
                - action: sync
                  path: ./frontend
                  target: /usr/src/app
                - action: rebuild
                  path: ./frontend/package.json

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "3000:${EXPRESS_PORT}"
        depends_on:
            - mongodb
        command: npm run dev
        develop:
            watch:
                - action: sync
                  path: ./backend
                  target: /usr/src/app
                - action: rebuild
                  path: ./backend/package.json

    mongodb:
        image: mongo:latest
        ports:
            - 27018:${MONGO_PORT}
        env_file:
            - .env
        volumes:
            - mongodb_data:/data/db

    redis:
        image: redis:latest
        container_name: redis
        ports:
        - "6378:${REDIS_PORT}"

volumes:
    mongodb_data:
